import { SiteFooter } from "./components/SiteFooter";
import { SiteNav as SharedSiteNav } from "./components/SiteNav";
import { useEffect, useState } from "react";
import { ArrowRight, Check, ChevronRight } from "lucide-react";
import { motion } from "motion/react";
import { Link } from "react-router";
import { applySeo } from "./seo";


function SiteNav() {
  return <SharedSiteNav />;
}

const packages = [
  ["Seed", "Focused launches", "For a clear first digital move.", ["Brand direction", "One focused landing page", "Launch-ready handover"]],
  ["Canopy", "Growth systems", "For businesses ready to connect the pieces.", ["Strategy workshop", "Multi-page website", "Core identity system", "Analytics setup"]],
  ["Evergreen", "Ongoing partnership", "For teams that want an embedded digital studio.", ["Monthly creative direction", "Site evolution & support", "Campaign and growth input", "Priority working rhythm"]],
];

export function PackagesPage() {
  useEffect(() => { applySeo({ title: "Digital Agency Packages | MBK.GLOBAL", description: "Explore MBK.GLOBAL engagement options for focused launches, growth systems and ongoing digital partnership.", pathname: "/packages" }); }, []);
  return <main id="main-content" tabIndex={-1} className="min-h-screen bg-background font-['Plus_Jakarta_Sans'] text-foreground"><SiteNav /><section className="border-b border-border px-5 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-7xl"><p className="font-['DM_Mono'] text-[10px] uppercase tracking-[.14em] text-muted-foreground">Engagement models / A place to begin</p><h1 className="mt-7 max-w-5xl font-['Fraunces'] text-[clamp(2.65rem,7vw,6.5rem)] font-semibold leading-[1.02] tracking-[-.04em]">Good work has a <i className="font-medium text-primary">clear way in.</i></h1><p className="mt-8 max-w-xl leading-7 text-muted-foreground">Three considered starting points. Each becomes a tailored scope after we understand the opportunity.</p></div></section><section className="px-5 py-16 md:px-10"><div className="mx-auto grid max-w-7xl gap-px bg-border lg:grid-cols-3">{packages.map(([name, type, copy, items], index) => <article key={name} className="group bg-background p-7 transition duration-300 hover:bg-secondary md:p-9"><p className="font-['DM_Mono'] text-xs text-primary">0{index + 1}</p><h2 className="mt-14 font-['Fraunces'] text-4xl font-semibold">{name}</h2><p className="mt-2 text-sm font-semibold">{type}</p><p className="mt-5 min-h-12 text-sm leading-6 text-muted-foreground">{copy}</p><ul className="mt-10 grid gap-3 border-t border-border pt-6">{items.map(item => <li key={item} className="flex gap-3 text-sm"><Check size={16} className="shrink-0 text-primary" />{item}</li>)}</ul><Link to="/project-planner" className="mt-12 inline-flex items-center gap-2 text-sm font-semibold text-primary group-hover:text-foreground">Explore fit <ArrowRight size={16} /></Link></article>)}</div></section><SiteFooter /></main>;
}

const steps = ["Your details", "What you need", "Project shape", "Submit brief"];
export function ProjectPlannerPage() {
  const [step, setStep] = useState(0); const [sent, setSent] = useState(false);
  const [planner, setPlanner] = useState({ name: "", email: "", need: "", scope: "" });
  useEffect(() => { applySeo({ title: "Project Planner | MBK.GLOBAL", description: "Share your website, branding, marketing or AI project goals with MBK.GLOBAL and receive a clear next step.", pathname: "/project-planner", noIndex: true }); }, []);
  const next = () => setStep(s => Math.min(s + 1, steps.length - 1));
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (step < 3) { next(); return; } const text = `*New MBK.GLOBAL project planner brief*\n\nName: ${planner.name}\nEmail: ${planner.email}\nNeed: ${planner.need}\nProject shape: ${planner.scope}`; setSent(true); window.open(`https://wa.me/923200276941?text=${encodeURIComponent(text)}`, "_blank", "noopener,noreferrer"); };
  return <main id="main-content" tabIndex={-1} className="min-h-screen bg-background font-['Plus_Jakarta_Sans'] text-foreground"><SiteNav /><section className="px-5 py-14 md:px-10 md:py-20"><div className="mx-auto max-w-4xl"><p className="font-['DM_Mono'] text-[10px] uppercase tracking-[.14em] text-muted-foreground">Project planner / 4 minute brief</p><h1 className="mt-5 font-['Fraunces'] text-[clamp(3.3rem,7vw,6rem)] font-semibold leading-[.88] tracking-[-.04em]">Give your next idea <i className="font-medium text-primary">a shape.</i></h1><div className="mt-12 grid grid-cols-4 border-y border-border">{steps.map((label, index) => <div key={label} className={`py-4 text-center font-['DM_Mono'] text-[9px] uppercase tracking-[.09em] ${index <= step ? "text-primary" : "text-muted-foreground"}`}>0{index + 1}<span className="hidden sm:inline"> / {label}</span></div>)}</div><motion.form key={step} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} onSubmit={submit} className="mt-10 border border-border bg-card p-6 md:p-10">{sent ? <div className="py-10 text-center"><p className="font-['Fraunces'] text-4xl font-semibold text-primary">Brief ready to send.</p><p className="mt-4 text-sm text-muted-foreground">WhatsApp has opened with your project details.</p></div> : <PlannerStep step={step} planner={planner} setPlanner={setPlanner} />} {!sent && <div className="mt-10 flex items-center justify-between border-t border-border pt-5"><span className="font-['DM_Mono'] text-[10px] uppercase tracking-[.1em] text-muted-foreground">Step {step + 1} of 4</span><button className="inline-flex min-h-12 items-center gap-2 bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">{step === 3 ? "Send via WhatsApp" : "Continue"} <ChevronRight size={16} /></button></div>}</motion.form></div></section><SiteFooter /></main>;
}

function PlannerStep({ step, planner, setPlanner }: { step: number; planner: { name: string; email: string; need: string; scope: string }; setPlanner: React.Dispatch<React.SetStateAction<{ name: string; email: string; need: string; scope: string }>> }) {
  const content = [<><label className="text-sm font-semibold" htmlFor="name">Who should we speak with?</label><input id="name" autoComplete="name" required value={planner.name} onChange={e => setPlanner(v => ({ ...v, name: e.target.value }))} placeholder="Your name and company" className="mt-4 w-full border-b border-foreground/20 bg-transparent py-3 text-sm outline-none focus:border-primary" /><input aria-label="Work email" autoComplete="email" required value={planner.email} onChange={e => setPlanner(v => ({ ...v, email: e.target.value }))} type="email" placeholder="Work email" className="mt-5 w-full border-b border-foreground/20 bg-transparent py-3 text-sm outline-none focus:border-primary" /></>, <><p className="text-sm font-semibold">What are you looking to make better?</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{["Website or platform", "Brand identity", "Growth & marketing", "AI / business systems"].map(x => <label key={x} className="cursor-pointer border border-border p-4 text-sm hover:border-primary"><input required checked={planner.need === x} onChange={() => setPlanner(v => ({ ...v, need: x }))} type="radio" name="need" className="mr-3 accent-primary" />{x}</label>)}</div></>, <><label className="text-sm font-semibold" htmlFor="scope">Tell us the useful context</label><textarea id="scope" required value={planner.scope} onChange={e => setPlanner(v => ({ ...v, scope: e.target.value }))} placeholder="Goals, timeline, audience, current challenge…" className="mt-4 min-h-36 w-full border-b border-foreground/20 bg-transparent py-3 text-sm outline-none focus:border-primary" /></>, <><p className="font-['Fraunces'] text-3xl font-semibold">Ready when you are.</p><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">Your completed brief will open in WhatsApp, ready to send directly to our team at 03200276941.</p></>]; return content[step];
}
